backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "public/images/testimonials"
public_folder: "/images/testimonials"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Testimonial"
    name: "testimonial"
    folder: "src/testimonials"
    create: true
    slug: '{{pageName}}'
    editor:
      preview: false
    fields:
      - { label: 'Page-Name-with-dashes-only', name: 'pageName', widget: 'string' }
      - { label: 'Quote', name: 'quote', widget: 'string'}
      - { label: 'Author', name: 'author', widget: 'string'}
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['testimonial'] }
      - { label: 'Organization', name: 'organization', widget: 'string'}